sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.120.33.1
    port: 3306
    database: sky_take_out
    username: root
    password: 52ms1.MYSQL
  servlet:
    multipart:
      max-file-size: 2MB
  redis:
    host: 47.120.33.1
    port: 6379
    password: 52ms1.REDIS
    database: 9

  alioss:
    endpoint: "oss-cn-heyuan.aliyuncs.com"
    bucket-name: "sky-take-out-aidenchen"
